[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = false
build-info = true
extra_output = ["storageLayout"]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
base-sepolia = "https://base-sepolia.drpc.org"
base = "https://base-rpc.publicnode.com"

[etherscan]
84532 = { key = "8WWM95SRNZP4YUQ95TDBSPWR44RQY2CFIG", url = "https://api.etherscan.io/v2/api?chainid=84532" }
8453 = { key = "8WWM95SRNZP4YUQ95TDBSPWR44RQY2CFIG", url = "https://api.etherscan.io/v2/api?chainid=8453" }